# Generated by Django 5.2.5 on 2025-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='control_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
