# Generated by Django 5.2.5 on 2025-08-14 08:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sample_control_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
