# Generated by Django 5.2.5 on 2025-08-15 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_customer_contact_info_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='assigned_to_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='assigned_to_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='assigned_to_hodv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hodv_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Awaiting HOD Review', 'Awaiting HOD Review'), ('Awaiting HODv Assignment', 'Awaiting HODv Assignment'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Sent to DPF', 'Sent to DPF')], default='Registered', max_length=50),
        ),
    ]
