# Generated by Django 5.2.5 on 2025-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_testcatalog_test_price_test_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='testcatalog',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='myapp.ingredient'),
        ),
    ]
