# Generated by Django 5.2.5 on 2025-08-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ingredient_testcatalog_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='available_test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sample',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='samples', to='myapp.ingredient'),
        ),
        migrations.AddField(
            model_name='test',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ingredient'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_details',
            field=models.TextField(blank=True, help_text='Type of sample provided by the customer (e.g., Blood, Water)', null=True),
        ),
        migrations.DeleteModel(
            name='TestCatalog',
        ),
    ]
