# Generated by Django 5.2.5 on 2025-08-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_test_available_test_remove_test_test_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='ingredients',
        ),
    ]
