# Generated by Django 5.2.5 on 2025-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_sample_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='test_type',
            field=models.CharField(choices=[('Microbiology', 'Microbiology'), ('Chemistry', 'Chemistry')], default='Microbiology', max_length=50),
        ),
    ]
