# Generated by Django 5.2.5 on 2025-08-26 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_ingredient_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
