# Generated by Django 5.2.5 on 2025-08-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_test_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Awaiting HOD Review', 'Awaiting HOD Review'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Sent to DPF', 'Sent to DPF')], default='Registered', max_length=50),
        ),
    ]
