# Generated by Django 5.2.5 on 2025-08-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_sample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_set', to='myapp.sample'),
        ),
    ]
