# Generated by Django 5.2.5 on 2025-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_customer_address_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, help_text="Short name of the sample (e.g., 'Blood Sample A')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_details',
            field=models.TextField(blank=True, help_text='Type or description of the sample (e.g., Blood, Water)', null=True),
        ),
    ]
