# Generated by Django 5.2.5 on 2025-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_sample_sample_name_alter_sample_sample_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='control_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
