# Generated by Django 5.2.5 on 2025-09-11 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_sample_control_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='control_number',
            field=models.CharField(blank=True, help_text='System-generated or manually entered control number.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='myapp.customer'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_details',
            field=models.TextField(blank=True, help_text='Detailed description of the sample.', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, help_text='Short title or name for the sample (e.g., Water Sample, Soil Sample).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Awaiting HOD Review', 'Awaiting HOD Review'), ('Submitted to HOD', 'Submitted to HOD'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Sent to DPF', 'Sent to DPF')], default='Registered', max_length=50),
        ),
    ]
