# Generated by Django 5.2.5 on 2025-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_sample_control_number_alter_sample_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Chemistry', 'Chemistry'), ('Microbiology', 'Microbiology')], help_text='Only applies if role is Technician', max_length=50, null=True),
        ),
    ]
