# Generated by Django 5.2.5 on 2025-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_submitted_to_hod',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
