# Generated by Django 5.2.5 on 2025-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_sample_date_submitted_to_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='date_submitted_to_hod',
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Awaiting Registrar Approval', 'Awaiting Registrar Approval'), ('Awaiting HOD Review', 'Awaiting HOD Review'), ('Submitted to HOD', 'Submitted to HOD'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Sent to DPF', 'Sent to DPF')], default='Registered', max_length=50),
        ),
    ]
