# Generated by Django 5.2.5 on 2025-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='laboratory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
