# Generated by Django 5.2.5 on 2025-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_sample_laboratory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting DG Review', 'Awaiting DG Review'), ('Awaiting HOD Review', 'Awaiting HOD Review'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
