# Generated by Django 5.2.5 on 2025-09-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_test_status_alter_verificationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting DG Review', 'Awaiting DG Review'), ('Awaiting HOD Review', 'Awaiting HOD Review'), ('Completed', 'Completed'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
