# Generated by Django 5.2.5 on 2025-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Registrar', 'Registrar'), ('HOD', 'Head of Department'), ('HODv', 'Head of Division'), ('Technician', 'Laboratory Technician'), ('Director General', 'Director General')], default='Technician', max_length=50),
        ),
    ]
